// Generated by scripts/generate-command-data.ts. Do not edit by hand.
namespace BidiLens;
internal static class TechnicalCommands
{
    private static readonly Dictionary<string, HashSet<string>> Verbs = new(StringComparer.Ordinal)
    {
        ["npm"] = new("install i ci run test start build exec publish init update uninstall audit pack login".Split(' ', StringSplitOptions.RemoveEmptyEntries), StringComparer.Ordinal),
        ["pnpm"] = new("install i add remove run test start build exec dlx publish init update audit".Split(' ', StringSplitOptions.RemoveEmptyEntries), StringComparer.Ordinal),
        ["yarn"] = new("install add remove run test start build exec dlx publish init upgrade".Split(' ', StringSplitOptions.RemoveEmptyEntries), StringComparer.Ordinal),
        ["npx"] = new("".Split(' ', StringSplitOptions.RemoveEmptyEntries), StringComparer.Ordinal),
        ["git"] = new("status diff add commit push pull fetch clone checkout switch branch log show merge rebase tag init remote reset restore".Split(' ', StringSplitOptions.RemoveEmptyEntries), StringComparer.Ordinal),
        ["pip"] = new("install uninstall list freeze show check download wheel".Split(' ', StringSplitOptions.RemoveEmptyEntries), StringComparer.Ordinal),
        ["python"] = new("".Split(' ', StringSplitOptions.RemoveEmptyEntries), StringComparer.Ordinal),
        ["node"] = new("".Split(' ', StringSplitOptions.RemoveEmptyEntries), StringComparer.Ordinal),
        ["cargo"] = new("build check run test clippy fmt install update publish new init clean doc".Split(' ', StringSplitOptions.RemoveEmptyEntries), StringComparer.Ordinal),
        ["go"] = new("build run test mod get install fmt vet version env clean generate tool".Split(' ', StringSplitOptions.RemoveEmptyEntries), StringComparer.Ordinal),
        ["docker"] = new("run build compose pull push images image ps exec stop start rm rmi logs inspect".Split(' ', StringSplitOptions.RemoveEmptyEntries), StringComparer.Ordinal),
        ["kubectl"] = new("get describe apply delete create edit logs exec config rollout scale version".Split(' ', StringSplitOptions.RemoveEmptyEntries), StringComparer.Ordinal),
    };
    internal static bool IsCommandArgument(string executable, string argument) =>
        Verbs.TryGetValue(executable, out var verbs) && (verbs.Contains(argument)
            || System.Text.RegularExpressions.Regex.IsMatch(argument, @"^--?[A-Za-z0-9_-]+$", System.Text.RegularExpressions.RegexOptions.CultureInvariant)
            || argument.IndexOfAny(['.', '/', '\\', '@', ':', '=']) >= 0
            || (argument.Length >= 2 && argument[0] is '\'' or '"' && argument[^1] == argument[0]));
}
