import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import process from 'node:process';

type Direction = 'ltr' | 'rtl' | 'neutral' | 'auto';
type CorpusIsolation = {
  text: string;
  direction: Direction;
  kind: string;
};
type CorpusCase = {
  id: string;
  text: string;
  expected: Exclude<Direction, 'auto'>;
  expectedIsolations?: CorpusIsolation[];
};

const sourcePath = resolve('corpus/cases.json');
const outputPath = resolve(
  'android/core/src/test/kotlin/io/github/codeinscrubs/bidilens/core/GeneratedCorpusFixtures.kt'
);

function kotlinString(value: string): string {
  const jsonBody = JSON.stringify(value).slice(1, -1);
  return `"${jsonBody.replaceAll('$', '\\$')}"`;
}

function direction(value: Direction): string {
  if (value === 'rtl') return 'BidiDirection.RTL';
  if (value === 'ltr') return 'BidiDirection.LTR';
  return 'BidiDirection.NEUTRAL';
}

function isolationKind(value: string): string {
  return `BidiIsolationKind.${value.replaceAll('-', '_').toUpperCase()}`;
}

function render(cases: readonly CorpusCase[]): string {
  const fixtures = cases.map((item) => {
    const isolations = (item.expectedIsolations ?? []).map((isolation) =>
      `            ExpectedIsolation(${kotlinString(isolation.text)}, ${direction(isolation.direction)}, ${isolationKind(isolation.kind)})`
    ).join(',\n');
    const isolationValue = item.expectedIsolations === undefined
      ? 'null'
      : `listOf(
${isolations}
            )`;
    return `        CorpusFixture(
            id = ${kotlinString(item.id)},
            text = ${kotlinString(item.text)},
            expected = ${direction(item.expected)},
            isolations = ${isolationValue},
        )`;
  }).join(',\n');

  return `// Generated by scripts/generate-android-corpus.ts. Do not edit by hand.
package io.github.codeinscrubs.bidilens.core

internal data class ExpectedIsolation(
    val text: String,
    val direction: BidiDirection,
    val kind: BidiIsolationKind,
)

internal data class CorpusFixture(
    val id: String,
    val text: String,
    val expected: BidiDirection,
    val isolations: List<ExpectedIsolation>?,
)

internal val generatedCorpusFixtures = listOf(
${fixtures}
)
`;
}

const cases = JSON.parse(await readFile(sourcePath, 'utf8')) as CorpusCase[];
const generated = render(cases);
if (process.argv.includes('--check')) {
  const current = await readFile(outputPath, 'utf8');
  if (current !== generated) {
    throw new Error('Generated Android corpus is stale. Run pnpm corpus:generate.');
  }
  console.log(`Android corpus representation is reproducible (${cases.length} fixtures).`);
} else {
  await mkdir(dirname(outputPath), { recursive: true });
  await writeFile(outputPath, generated, 'utf8');
  console.log(`Generated Android corpus representation (${cases.length} fixtures).`);
}
