import { createHash } from 'node:crypto';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import process from 'node:process';

const UNICODE_VERSION = '17.0.0';
const BIDI_SHA256 = '4867b4b7f0731ed1bfcd34cc6251211ff1542541fce0734b6fbda139ee80b3a4';
const GENERAL_CATEGORY_SHA256 = 'd62e5bab70ca74f099343f71224fa051cb1fdd61a1ab45c0488c44cfc0b6102e';
const BIDI_URL = `https://www.unicode.org/Public/${UNICODE_VERSION}/ucd/extracted/DerivedBidiClass.txt`;
const GENERAL_CATEGORY_URL = `https://www.unicode.org/Public/${UNICODE_VERSION}/ucd/extracted/DerivedGeneralCategory.txt`;
const BIDI_PATH = resolve(`unicode/DerivedBidiClass-${UNICODE_VERSION}.txt`);
const GENERAL_CATEGORY_PATH = resolve(`unicode/DerivedGeneralCategory-${UNICODE_VERSION}.txt`);
const OUTPUT_PATH = resolve('packages/core/src/generated/bidi-ranges.ts');

interface UnicodeSource {
  label: string;
  url: string;
  path: string;
  sha256: string;
}

const CLASS = {
  L: 0,
  R: 1,
  AL: 2,
  OTHER: 3
} as const;

function normalizeClass(value: string): number {
  if (value === 'L' || value === 'Left_To_Right') return CLASS.L;
  if (value === 'R' || value === 'Right_To_Left') return CLASS.R;
  if (value === 'AL' || value === 'Arabic_Letter') return CLASS.AL;
  return CLASS.OTHER;
}

function parseRange(value: string): readonly [number, number] {
  const [startText, endText = startText] = value.trim().split('..');
  if (!startText || !endText) throw new Error(`Invalid Unicode range: ${value}`);
  return [Number.parseInt(startText, 16), Number.parseInt(endText, 16)];
}

function assignRange(classes: Uint8Array, range: string, bidiClass: string): void {
  const [start, end] = parseRange(range);
  classes.fill(normalizeClass(bidiClass), start, end + 1);
}

function parseDerivedGeneralCategory(source: string): Uint8Array {
  const letters = new Uint8Array(0x110000);
  for (const line of source.split(/\r?\n/u)) {
    const data = line.split('#', 1)[0]?.trim();
    if (!data) continue;
    const match = data.match(/^([0-9A-F.]+)\s*;\s*(L[ultmo])$/u);
    if (!match?.[1]) continue;
    const [start, end] = parseRange(match[1]);
    letters.fill(1, start, end + 1);
  }
  return letters;
}

function parseDerivedBidiClass(source: string): Uint8Array {
  // UCD's global @missing value is L. Specific @missing ranges override it,
  // and explicit records override all @missing values.
  const classes = new Uint8Array(0x110000);
  const lines = source.split(/\r?\n/u);

  for (const line of lines) {
    const match = line.match(/^#\s*@missing:\s*([0-9A-F.]+)\s*;\s*([A-Za-z_]+)/u);
    if (match?.[1] && match[2]) assignRange(classes, match[1], match[2]);
  }

  for (const line of lines) {
    const data = line.split('#', 1)[0]?.trim();
    if (!data) continue;
    const match = data.match(/^([0-9A-F.]+)\s*;\s*([A-Z]+)/u);
    if (match?.[1] && match[2]) assignRange(classes, match[1], match[2]);
  }
  return classes;
}

function collectRanges(classes: Uint8Array, predicate: (value: number) => boolean): Array<readonly [number, number]> {
  const ranges: Array<readonly [number, number]> = [];
  let start = -1;
  for (let codePoint = 0; codePoint <= 0x10ffff; codePoint += 1) {
    if (predicate(classes[codePoint]!)) {
      if (start < 0) start = codePoint;
    } else if (start >= 0) {
      ranges.push([start, codePoint - 1]);
      start = -1;
    }
  }
  if (start >= 0) ranges.push([start, 0x10ffff]);
  return ranges;
}

function renderRanges(name: string, ranges: ReadonlyArray<readonly [number, number]>): string {
  const values = ranges.map(([start, end]) => `  0x${start.toString(16)}, 0x${end.toString(16)}`).join(',\n');
  return `export const ${name}: ReadonlyArray<number> = [\n${values}\n];`;
}

function generate(bidiSource: string, generalCategorySource: string): string {
  const classes = parseDerivedBidiClass(bidiSource);
  const letters = parseDerivedGeneralCategory(generalCategorySource);
  const rtl = collectRanges(classes, (value) => value === CLASS.R || value === CLASS.AL);
  const nonStrong = collectRanges(classes, (value) => value === CLASS.OTHER);
  const naturalLetters = collectRanges(letters, (value) => value === 1);
  return `// Generated by scripts/generate-bidi-data.ts. Do not edit by hand.
// Source: ${BIDI_URL}
// SHA-256: ${BIDI_SHA256}
// Source: ${GENERAL_CATEGORY_URL}
// SHA-256: ${GENERAL_CATEGORY_SHA256}

export const UNICODE_BIDI_VERSION = '${UNICODE_VERSION}';
export const UNICODE_BIDI_SHA256 = '${BIDI_SHA256}';
export const UNICODE_GENERAL_CATEGORY_SHA256 = '${GENERAL_CATEGORY_SHA256}';

${renderRanges('RTL_BIDI_RANGES', rtl)}

${renderRanges('NON_STRONG_BIDI_RANGES', nonStrong)}

${renderRanges('NATURAL_LETTER_RANGES', naturalLetters)}
`;
}

async function sourceBytes(source: UnicodeSource, download: boolean): Promise<Uint8Array> {
  let bytes: Uint8Array;
  if (download) {
    const response = await fetch(source.url);
    if (!response.ok) throw new Error(`${source.label} download failed: HTTP ${response.status}`);
    bytes = new Uint8Array(await response.arrayBuffer());
  } else {
    bytes = await readFile(source.path);
  }
  const actualSha256 = createHash('sha256').update(bytes).digest('hex');
  if (actualSha256 !== source.sha256) {
    throw new Error(`${source.label} checksum mismatch: expected ${source.sha256}, received ${actualSha256}`);
  }
  if (download) {
    await mkdir(dirname(source.path), { recursive: true });
    await writeFile(source.path, bytes);
  }
  return bytes;
}

async function main(): Promise<void> {
  const download = process.argv.includes('--download');
  const check = process.argv.includes('--check');
  const bidiSource: UnicodeSource = {
    label: 'DerivedBidiClass', url: BIDI_URL, path: BIDI_PATH, sha256: BIDI_SHA256
  };
  const generalCategorySource: UnicodeSource = {
    label: 'DerivedGeneralCategory',
    url: GENERAL_CATEGORY_URL,
    path: GENERAL_CATEGORY_PATH,
    sha256: GENERAL_CATEGORY_SHA256
  };
  const [bidiBytes, generalCategoryBytes] = await Promise.all([
    sourceBytes(bidiSource, download),
    sourceBytes(generalCategorySource, download)
  ]);
  const generated = generate(
    new TextDecoder().decode(bidiBytes),
    new TextDecoder().decode(generalCategoryBytes)
  );
  if (check) {
    const current = await readFile(OUTPUT_PATH, 'utf8');
    if (current !== generated) throw new Error('Generated bidi data is stale. Run pnpm unicode:generate.');
    console.log(`Unicode ${UNICODE_VERSION} bidi and letter data are reproducible (${BIDI_SHA256}; ${GENERAL_CATEGORY_SHA256}).`);
    return;
  }
  await mkdir(dirname(OUTPUT_PATH), { recursive: true });
  await writeFile(OUTPUT_PATH, generated, 'utf8');
  console.log(`Generated ${OUTPUT_PATH} from Unicode ${UNICODE_VERSION} bidi and letter data.`);
}

await main();
