import { createHash } from 'node:crypto';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';

const version = '17.0.0';
const sources = [
  ['auxiliary/GraphemeBreakProperty.txt', 'GraphemeBreakProperty', 'd6b51d1d2ae5c33b451b7ed994b48f1f4dc62b2272a5831e7fd418514a6bae89'],
  ['DerivedCoreProperties.txt', 'DerivedCoreProperties', '24c7fed1195c482faaefd5c1e7eb821c5ee1fb6de07ecdbaa64b56a99da22c08'],
  ['emoji/emoji-data.txt', 'emoji-data', '2cb2bb9455cda83e8481541ecf5b6dfda66a3bb89efa3fa7c5297eccf607b72b'],
  ['auxiliary/GraphemeBreakTest.txt', 'GraphemeBreakTest', 'e2d134d2c52919bace503ebb6a551c1855fe1a1faec18478c78fff254a1793ec']
] as const;
const check = process.argv.includes('--check');
const download = process.argv.includes('--download');
if (check && download) throw new Error('--check is offline; do not combine it with --download.');
const texts: string[] = [];
for (const [upstream, name, hash] of sources) {
  const path = resolve(`unicode/${name}-${version}.txt`);
  const bytes = download ? await (async () => {
    const response = await fetch(`https://www.unicode.org/Public/${version}/ucd/${upstream}`);
    if (!response.ok) throw new Error(`${upstream}: HTTP ${response.status}`);
    return Buffer.from(await response.arrayBuffer());
  })() : await readFile(path);
  if (createHash('sha256').update(bytes).digest('hex') !== hash) throw new Error(`Checksum mismatch: ${name}`);
  if (download) await writeFile(path, bytes);
  texts.push(bytes.toString('utf8'));
}

const properties = new Map<string, Array<[number, number]>>();
for (const [index, source] of texts.entries()) {
  if (index === 3) break; // official test vectors are vendored but not runtime data
  for (const line of source.split(/\r?\n/u)) {
    const data = line.split('#')[0]!.trim();
    if (!data) continue;
    const fields = data.split(';').map((field) => field.trim());
    const property = index === 0 ? `GCB_${fields[1]}`
      : index === 1 && fields[1] === 'InCB' ? `INCB_${fields[2]}`
        : index === 2 && fields[1] === 'Extended_Pictographic' ? 'EXTENDED_PICTOGRAPHIC' : '';
    if (!property) continue;
    const [first, last = first] = fields[0]!.split('..');
    const ranges = properties.get(property) ?? [];
    ranges.push([Number.parseInt(first!, 16), Number.parseInt(last!, 16)]);
    properties.set(property, ranges);
  }
}
const lines = [
  '// Generated by scripts/generate-grapheme-data.ts. Do not edit.',
  '// Unicode 17.0.0, UAX #29 extended grapheme clusters. Source SHA-256 pins are in the generator.',
  '// Unicode data license: https://www.unicode.org/license.txt',
  "import { decodeRangeDeltas } from '../unicode-ranges.js';", ''
];
for (const [property, input] of [...properties].sort(([a], [b]) => a.localeCompare(b))) {
  const ranges: Array<[number, number]> = [];
  for (const [start, end] of input.sort(([a], [b]) => a - b)) {
    const previous = ranges.at(-1);
    if (previous && start <= previous[1] + 1) previous[1] = Math.max(previous[1], end);
    else ranges.push([start, end]);
  }
  let previousEnd = -1;
  const encoded = ranges.flatMap(([start, end]) => {
    const values = [(start - previousEnd - 1).toString(36), (end - start).toString(36)];
    previousEnd = end;
    return values;
  }).join(',');
  lines.push(`export const ${property.toUpperCase()} = decodeRangeDeltas('${encoded}');`);
}
const output = lines.join('\n') + '\n';
const target = resolve('packages/core/src/generated/grapheme-ranges.ts');
if (check) {
  if (await readFile(target, 'utf8') !== output) throw new Error('Generated grapheme ranges are stale.');
} else {
  await mkdir(dirname(target), { recursive: true });
  await writeFile(target, output);
}
console.log(`Unicode ${version} grapheme sources and generated ranges ${check ? 'verified' : 'generated'}.`);
