import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { mkdir, readFile, readdir, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { chromium } from '@playwright/test';
import MarkdownIt from 'markdown-it';
import { escapeHtml, renderBidiHtml } from '../packages/html/src/index.js';
import { markdownItBidi } from '../packages/markdown/src/index.js';

/** Real browser captures, never drawn, reordered, or generated by an image model. */
const cases = [
  {
    id: 'persian-leading-identifier',
    title: 'A Latin first word in Persian prose',
    source: 'React یک کتابخانه جاوااسکریپت بسیار محبوب است.',
    baseline: 'auto',
    directions: ['rtl'],
    alignment: 'start',
    explanation: 'HTML dir=auto follows the Latin first word. The requested Persian paragraph base is RTL; React remains an LTR isolate.'
  },
  {
    id: 'persian-aligned-left',
    title: 'RTL order with physical left alignment',
    source: 'React یک کتابخانه جاوااسکریپت بسیار محبوب است.',
    baseline: 'auto',
    directions: ['rtl'],
    alignment: 'left',
    explanation: 'The host keeps text-align:left. Direction and isolation change the reading order without moving the paragraph to the right edge.'
  },
  {
    id: 'english-in-rtl-host',
    title: 'English prose inside an RTL container',
    source: 'The Persian word کتاب means “book”.',
    baseline: 'rtl',
    directions: ['ltr'],
    alignment: 'left',
    explanation: 'An inherited RTL base is inappropriate for this English sentence. BidiLens supplies an LTR block and isolates the Persian word.'
  },
  {
    id: 'independent-paragraphs',
    title: 'Independent message paragraph directions',
    source: 'The Persian word کتاب means “book”.\nReact یک کتابخانه جاوااسکریپت بسیار محبوب است.',
    baseline: 'ltr',
    directions: ['ltr', 'rtl'],
    alignment: 'left',
    explanation: 'One global LTR setting cannot express both paragraphs. The renderer supplies separate bases while preserving physical left alignment.'
  },
  {
    id: 'technical-phrase',
    title: 'An ordered technical phrase in Persian prose',
    source: 'این قسمت برای brainstem localization nuclei of IX and X in medulla مهم می‌شود.',
    baseline: 'ltr',
    directions: ['rtl'],
    alignment: 'left',
    explanation: 'Domain terms are declared as technical identifiers. Caller knowledge supplies the intended Persian base where majority evidence alone is ambiguous.',
    identifiers: ['brainstem', 'localization', 'nuclei', 'medulla']
  },
  {
    id: 'mixed-markdown',
    title: 'AI-style Markdown with lists, quotes, and code',
    source: [
      '## React یک کتابخانه بسیار محبوب است.', '',
      '- API یک رابط برنامه‌نویسی کاربردی است.',
      '- The Persian word کتاب means book.', '',
      '> React یک کتابخانه بسیار محبوب است.', '',
      '| Feature | توضیح |', '| --- | --- |',
      '| streaming | پردازش جریانی بسیار سریع است |', '',
      'مسیر فایل `src/app.ts` در پروژه قرار دارد.', '',
      '```ts', 'const message = "سلام";', '```'
    ].join('\n'),
    baseline: 'ltr',
    directions: [],
    alignment: 'left',
    explanation: 'Markdown-It is rendered with and without the actual BidiLens plugin. Heading, list, quote, cell, and code boundaries retain their own direction.',
    markdown: true
  }
] as const;

const root = resolve('docs/problem-gallery');
const sha256 = (bytes: string | Buffer): string => createHash('sha256').update(bytes).digest('hex');
const textSha256 = (text: string): string => sha256(text.replaceAll('\r\n', '\n'));
const style = `
  html { background:#f3f4f6; color:#171717; font-family:Arial,sans-serif; }
  body { margin:0; }
  #sample { box-sizing:border-box; width:760px; padding:24px; background:white; }
  p { margin:0 0 12px; font-size:23px; line-height:1.8; }
  p:last-child { margin-bottom:0; }
  bdi, code, pre { unicode-bidi:isolate; }
  h2 { font-size:25px; }
  li, blockquote, td, th { font-size:19px; line-height:1.7; }
  table { width:100%; border-collapse:collapse; }
  th,td { border:1px solid #ccc; padding:8px; }
  blockquote { margin-inline:0; padding-inline:16px; border-inline-start:3px solid #aaa; }
  pre { padding:14px; background:#f3f4f6; white-space:pre-wrap; }
`;

function documentHtml(title: string, content: string, alignment: string, direction: string): string {
  return `<!doctype html><html lang="en"><meta charset="utf-8"><title>${escapeHtml(title)}</title>`
    + `<style>${style}</style><main id="sample" dir="${direction}" style="text-align:${alignment}">${content}</main></html>`;
}

async function implementationFiles(directory: string): Promise<string[]> {
  const files: string[] = [];
  for (const entry of await readdir(directory, { withFileTypes: true })) {
    const file = `${directory}/${entry.name}`;
    if (entry.isDirectory()) files.push(...await implementationFiles(file));
    else if (entry.name.endsWith('.ts') && !entry.name.endsWith('.test.ts')) files.push(file);
  }
  return files;
}
const sourceFiles = ['scripts/generate-problem-gallery.ts', 'package.json', 'pnpm-lock.yaml',
  ...await implementationFiles('packages/core/src'),
  ...await implementationFiles('packages/html/src'),
  ...await implementationFiles('packages/markdown/src')].sort();
const inputHashes = Object.fromEntries(await Promise.all(sourceFiles.map(async (file) => [file, textSha256(await readFile(file, 'utf8'))])));
const manifest = JSON.parse(await readFile('package.json', 'utf8')) as { version: string };

if (process.argv.includes('--check')) {
  const index = JSON.parse(await readFile(resolve(root, 'index.json'), 'utf8')) as {
    schemaVersion: number;
    sourceVersion: string;
    sourceSha256: Record<string, string>;
    cases: Array<{ id: string; sourceSha256: string; artifacts: Record<string, string> }>;
  };
  assert.equal(index.schemaVersion, 1);
  assert.equal(index.sourceVersion, manifest.version);
  assert.deepEqual(index.sourceSha256, inputHashes, 'Gallery source changed; regenerate captures.');
  assert.equal(index.cases.length, cases.length);
  assert.equal(new Set(index.cases.map((entry) => entry.id)).size, cases.length, 'Duplicate gallery case.');
  for (const item of cases) {
    const recorded = index.cases.find((entry) => entry.id === item.id);
    assert.ok(recorded, `Missing case: ${item.id}`);
    assert.equal(recorded.sourceSha256, sha256(item.source));
    assert.deepEqual(Object.keys(recorded.artifacts).sort(),
      ['after.html', 'after.png', 'before.html', 'before.png', 'evidence.json', 'source.txt'],
      `Incomplete artifact manifest: ${item.id}`);
    for (const [file, hash] of Object.entries(recorded.artifacts)) {
      const bytes = await readFile(resolve(root, item.id, file));
      assert.equal(file.endsWith('.png') ? sha256(bytes) : textSha256(bytes.toString('utf8')), hash, `Changed artifact: ${item.id}/${file}`);
    }
  }
  const originals = JSON.parse(await readFile(resolve(root, 'originals/manifest.json'), 'utf8')) as {
    images: Array<{ file: string; sha256: string }>;
  };
  assert.equal(originals.images.length, 4, 'The four reviewed encountered captures must remain recorded.');
  assert.equal(new Set(originals.images.map((entry) => entry.file)).size, 4, 'Duplicate original capture.');
  for (const original of originals.images) {
    assert.equal(sha256(await readFile(resolve(root, 'originals', original.file))), original.sha256, `Changed original: ${original.file}`);
  }
  console.log(`Problem gallery verified: ${cases.length} paired cases, source and artifact hashes.`);
  process.exit(0);
}

await mkdir(root, { recursive: true });
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 800, height: 1000 }, deviceScaleFactor: 1 });
const capturedAt = new Date().toISOString();
const entries = [];
try {
  for (const item of cases) {
    const directory = resolve(root, item.id);
    await mkdir(directory, { recursive: true });
    const markdown = 'markdown' in item && item.markdown;
    let before: string;
    let after: string;
    if (markdown) {
      before = new MarkdownIt({ html: false }).render(item.source);
      const parser = new MarkdownIt({ html: false });
      markdownItBidi(parser);
      after = parser.render(item.source);
    } else {
      before = item.source.split('\n').map((text) => `<p${item.baseline === 'auto' ? ' dir="auto"' : ''}>${escapeHtml(text)}</p>`).join('\n');
      after = renderBidiHtml(item.source, {
        inheritedDirection: item.baseline === 'rtl' ? 'rtl' : 'ltr',
        ...('identifiers' in item ? { technicalIdentifiers: item.identifiers } : {})
      }).html;
    }
    assert.ok(!after.includes('text-align'), 'Renderer must leave alignment to the host.');
    const artifacts: Record<string, string> = {};
    const observations: Record<string, unknown> = {};
    let beforeVisible = '';
    for (const [phase, content] of [['before', before], ['after', after]] as const) {
      const html = documentHtml(item.title, content, item.alignment, item.baseline === 'rtl' ? 'rtl' : 'ltr');
      await writeFile(resolve(directory, `${phase}.html`), html);
      artifacts[`${phase}.html`] = sha256(html);
      await page.setContent(html);
      await page.evaluate(() => document.fonts.ready);
      const sample = page.locator('#sample');
      const visible = await sample.textContent() ?? '';
      const evidence = await sample.evaluate((element) => ({
        text: element.textContent,
        paragraphs: Array.from(element.querySelectorAll('p')).map((paragraph) => ({
          text: paragraph.textContent,
          direction: getComputedStyle(paragraph).direction,
          alignment: getComputedStyle(paragraph).textAlign
        })),
        headingDirection: element.querySelector('h2') ? getComputedStyle(element.querySelector('h2')!).direction : null,
        blockquoteDirection: element.querySelector('blockquote') ? getComputedStyle(element.querySelector('blockquote')!).direction : null,
        cellDirections: Array.from(element.querySelectorAll('th,td')).map((cell) => getComputedStyle(cell).direction),
        isolations: Array.from(element.querySelectorAll('bdi')).map((isolate) => ({ text: isolate.textContent, direction: isolate.getAttribute('dir') }))
      }));
      if (phase === 'before') beforeVisible = visible;
      else {
        assert.equal(visible, beforeVisible, `${item.id}: visible logical source changed.`);
        if (!markdown) {
          assert.equal(visible, item.source, `${item.id}: plain text must match exactly.`);
          assert.deepEqual(evidence.paragraphs.map((paragraph) => paragraph.direction), [...item.directions], item.id);
        } else {
          assert.equal(evidence.headingDirection, 'rtl');
          assert.equal(evidence.blockquoteDirection, 'rtl');
          assert.deepEqual(evidence.cellDirections, ['ltr', 'rtl', 'ltr', 'rtl']);
          assert.equal(await sample.locator('li').nth(0).getAttribute('dir'), 'rtl');
          assert.equal(await sample.locator('li').nth(1).getAttribute('dir'), 'ltr');
          assert.equal(await sample.locator('pre code').getAttribute('dir'), 'ltr');
        }
        assert.ok(evidence.paragraphs.every((paragraph) => paragraph.alignment === item.alignment));
        // Verify logical browser selection rather than relying only on pixels.
        const selected = await sample.evaluate((element) => {
          const range = document.createRange(); range.selectNodeContents(element);
          const selection = window.getSelection()!; selection.removeAllRanges(); selection.addRange(range);
          const text = range.toString(); selection.removeAllRanges(); return text;
        });
        if (!markdown) assert.equal(selected, item.source);
        if (item.id === 'persian-leading-identifier' || item.id === 'persian-aligned-left') {
          const positions = await sample.evaluate((element) => {
            const paragraph = element.querySelector('p')!;
            const walker = document.createTreeWalker(paragraph, NodeFilter.SHOW_TEXT);
            const nodes: Text[] = [];
            for (let node = walker.nextNode(); node; node = walker.nextNode()) nodes.push(node as Text);
            const first = nodes[0]!;
            const last = nodes.at(-1)!;
            const firstWord = document.createRange(); firstWord.setStart(first, 0); firstWord.setEnd(first, 5);
            const period = document.createRange(); period.setStart(last, last.length - 1); period.setEnd(last, last.length);
            return { firstWordX: firstWord.getBoundingClientRect().x, periodX: period.getBoundingClientRect().x };
          });
          assert.ok(positions.firstWordX > positions.periodX, `${item.id}: React must be right of the final period.`);
          observations.wordOrderGeometry = positions;
        }
      }
      observations[phase] = evidence;
      const bytes = await sample.screenshot({ path: resolve(directory, `${phase}.png`), animations: 'disabled' });
      artifacts[`${phase}.png`] = sha256(bytes);
    }
    await writeFile(resolve(directory, 'source.txt'), item.source);
    artifacts['source.txt'] = sha256(item.source);
    const evidence = JSON.stringify({
      id: item.id, title: item.title, capturedAt, renderer: `Chromium ${browser.version()}`,
      artifactStatus: 'unreleased source checkout; not a deployed host integration',
      baseline: item.baseline, alignment: item.alignment, explanation: item.explanation,
      ...( 'identifiers' in item ? { technicalIdentifiers: item.identifiers } : {}),
      sourceSha256: sha256(item.source), observations
    }, null, 2) + '\n';
    await writeFile(resolve(directory, 'evidence.json'), evidence);
    artifacts['evidence.json'] = sha256(evidence);
    entries.push({ id: item.id, title: item.title, sourceSha256: sha256(item.source), artifacts });
  }
} finally {
  await browser.close();
}
await writeFile(resolve(root, 'index.json'), JSON.stringify({
  schemaVersion: 1, capturedAt, sourceVersion: manifest.version,
  artifactStatus: 'unreleased source checkout',
  textHashLineEndings: 'LF',
  platform: process.platform, viewport: { width: 800, height: 1000 },
  fontStack: 'Arial, sans-serif', sourceSha256: inputHashes, cases: entries
}, null, 2) + '\n');
console.log(`Captured and asserted ${cases.length} real-browser before/after pairs in docs/problem-gallery.`);
