import { readFile, writeFile } from 'node:fs/promises';
import { COMMAND_SUBCOMMANDS } from '../packages/core/src/commands.js';

const entries = Object.entries(COMMAND_SUBCOMMANDS);
const header = '// Generated by scripts/generate-command-data.ts. Do not edit by hand.\n';
const outputs = new Map<string, string>([
  ['windows/src/BidiLens.Core/TechnicalCommands.cs', `${header}namespace BidiLens;
internal static class TechnicalCommands
{
    private static readonly Dictionary<string, HashSet<string>> Verbs = new(StringComparer.Ordinal)
    {
${entries.map(([name, words]) => `        ["${name}"] = new("${words}".Split(' ', StringSplitOptions.RemoveEmptyEntries), StringComparer.Ordinal),`).join('\n')}
    };
    internal static bool IsCommandArgument(string executable, string argument) =>
        Verbs.TryGetValue(executable, out var verbs) && (verbs.Contains(argument)
            || System.Text.RegularExpressions.Regex.IsMatch(argument, @"^--?[A-Za-z0-9_-]+$", System.Text.RegularExpressions.RegexOptions.CultureInvariant)
            || argument.IndexOfAny(['.', '/', '\\\\', '@', ':', '=']) >= 0
            || (argument.Length >= 2 && argument[0] is '\\'' or '"' && argument[^1] == argument[0]));
}
`],
  ['apple/Sources/BidiLens/TechnicalCommands.swift', `${header}import Foundation
enum TechnicalCommands {
    private static let verbs: [String: Set<String>] = [
${entries.map(([name, words]) => `        "${name}": Set("${words}".split(separator: " ").map(String.init)),`).join('\n')}
    ]
    static func isCommandArgument(_ executable: String, _ argument: String) -> Bool {
        guard let known = verbs[executable] else { return false }
        return known.contains(argument)
            || argument.range(of: #"^--?[A-Za-z0-9_-]+$"#, options: .regularExpression) != nil
            || argument.contains(where: { "./\\\\@:=".contains($0) })
            || (argument.count >= 2 && (argument.first == "'" || argument.first == "\\"") && argument.last == argument.first)
    }
}
`],
  ['android/core/src/main/kotlin/io/github/codeinscrubs/bidilens/core/generated/TechnicalCommands.kt', `${header}package io.github.codeinscrubs.bidilens.core.generated
internal object TechnicalCommands {
    private val verbs = mapOf(
${entries.map(([name, words]) => `        "${name}" to "${words}".split(' ').filter { it.isNotEmpty() }.toSet(),`).join('\n')}
    )
    private val flag = Regex("^--?[A-Za-z0-9_-]+$")
    fun isCommandArgument(executable: String, argument: String): Boolean {
        val known = verbs[executable] ?: return false
        return argument in known || flag.matches(argument) || argument.any { it in "./\\\\@:=" }
            || (argument.length >= 2 && argument.first() in "'\\"" && argument.last() == argument.first())
    }
}
`],
  ['rust/src/generated/technical_commands.rs', `${header}#[rustfmt::skip]
pub(crate) fn is_command_argument(executable: &str, argument: &str) -> bool {
    let verbs = match executable {
${entries.map(([name, words]) => `        "${name}" => "${words}",`).join('\n')}
        _ => return false,
    };
    let flag = argument.strip_prefix('-').map(|rest| rest.strip_prefix('-').unwrap_or(rest));
    verbs.split_ascii_whitespace().any(|verb| verb == argument)
        || flag.is_some_and(|rest| !rest.is_empty() && rest.bytes().all(|c| c.is_ascii_alphanumeric() || c == b'_' || c == b'-'))
        || argument.contains(['.', '/', '\\\\', '@', ':', '='])
        || (argument.len() >= 2 && matches!(argument.as_bytes()[0], b'\\'' | b'"') && argument.as_bytes().last() == argument.as_bytes().first())
}
`]
]);
for (const [path, expected] of outputs) {
  if (process.argv.includes('--check')) {
    if (await readFile(path, 'utf8') !== expected) throw new Error(`Generated command recognizer is stale: ${path}`);
  } else await writeFile(path, expected, 'utf8');
}
console.log(`Curated command recognition data ${process.argv.includes('--check') ? 'verified' : 'generated'} for four native ports.`);
