// Generated by scripts/generate-command-data.ts. Do not edit by hand.
import Foundation
enum TechnicalCommands {
    private static let verbs: [String: Set<String>] = [
        "npm": Set("install i ci run test start build exec publish init update uninstall audit pack login".split(separator: " ").map(String.init)),
        "pnpm": Set("install i add remove run test start build exec dlx publish init update audit".split(separator: " ").map(String.init)),
        "yarn": Set("install add remove run test start build exec dlx publish init upgrade".split(separator: " ").map(String.init)),
        "npx": Set("".split(separator: " ").map(String.init)),
        "git": Set("status diff add commit push pull fetch clone checkout switch branch log show merge rebase tag init remote reset restore".split(separator: " ").map(String.init)),
        "pip": Set("install uninstall list freeze show check download wheel".split(separator: " ").map(String.init)),
        "python": Set("".split(separator: " ").map(String.init)),
        "node": Set("".split(separator: " ").map(String.init)),
        "cargo": Set("build check run test clippy fmt install update publish new init clean doc".split(separator: " ").map(String.init)),
        "go": Set("build run test mod get install fmt vet version env clean generate tool".split(separator: " ").map(String.init)),
        "docker": Set("run build compose pull push images image ps exec stop start rm rmi logs inspect".split(separator: " ").map(String.init)),
        "kubectl": Set("get describe apply delete create edit logs exec config rollout scale version".split(separator: " ").map(String.init)),
    ]
    static func isCommandArgument(_ executable: String, _ argument: String) -> Bool {
        guard let known = verbs[executable] else { return false }
        return known.contains(argument)
            || argument.range(of: #"^--?[A-Za-z0-9_-]+$"#, options: .regularExpression) != nil
            || argument.contains(where: { "./\\@:=".contains($0) })
            || (argument.count >= 2 && (argument.first == "'" || argument.first == "\"") && argument.last == argument.first)
    }
}
